-- MySQL Backup File
-- Database: Shanghai
-- Date: Sun Feb 22 02:45:20 CST 2026
-- Generated by Travel Prediction System

-- 注意：这是一个演示备份文件
-- 实际生产环境需要使用 mysqldump 工具
-- 命令示例：
-- mysqldump -uroot -p Shanghai > backup_manual_Shanghai_2026-02-22_024520.sql

