-- 初始化平台统计数据 (platform_statistics)
-- 生成最近90天的数据

-- 先清空旧数据
DELETE FROM platform_statistics WHERE stat_date >= DATE_SUB(CURDATE(), INTERVAL 90 DAY);

-- 插入最近90天的平台统计数据
INSERT INTO platform_statistics (stat_date, total_users, total_merchants, total_scenics, total_revenue, daily_visitors, daily_orders, daily_revenue, created_at)
SELECT 
    DATE_SUB(CURDATE(), INTERVAL seq.seq DAY) as stat_date,
    -- 总用户数：基础18人，每天增加0-2人
    18 + FLOOR(RAND() * 2 * (90 - seq.seq)) as total_users,
    -- 总商户数：固定5个
    5 as total_merchants,
    -- 总景区数：固定5个
    5 as total_scenics,
    -- 总收入：累计
    250000 + FLOOR(RAND() * 50000) + (90 - seq.seq) * 3000 as total_revenue,
    -- 日游客量：周末1500-2500，工作日800-1500
    CASE 
        WHEN DAYOFWEEK(DATE_SUB(CURDATE(), INTERVAL seq.seq DAY)) IN (1, 7) 
        THEN 1500 + FLOOR(RAND() * 1000)
        ELSE 800 + FLOOR(RAND() * 700)
    END as daily_visitors,
    -- 日订单量：游客量的50-70%
    CASE 
        WHEN DAYOFWEEK(DATE_SUB(CURDATE(), INTERVAL seq.seq DAY)) IN (1, 7) 
        THEN FLOOR((1500 + FLOOR(RAND() * 1000)) * (0.5 + RAND() * 0.2))
        ELSE FLOOR((800 + FLOOR(RAND() * 700)) * (0.5 + RAND() * 0.2))
    END as daily_orders,
    -- 日收入：人均80-120元
    CASE 
        WHEN DAYOFWEEK(DATE_SUB(CURDATE(), INTERVAL seq.seq DAY)) IN (1, 7) 
        THEN (1500 + FLOOR(RAND() * 1000)) * (80 + FLOOR(RAND() * 40))
        ELSE (800 + FLOOR(RAND() * 700)) * (80 + FLOOR(RAND() * 40))
    END as daily_revenue,
    NOW() as created_at
FROM (
    SELECT 0 as seq UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 
    UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9
    UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14
    UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19
    UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24
    UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29
    UNION SELECT 30 UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34
    UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39
    UNION SELECT 40 UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44
    UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49
    UNION SELECT 50 UNION SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54
    UNION SELECT 55 UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59
    UNION SELECT 60 UNION SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64
    UNION SELECT 65 UNION SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69
    UNION SELECT 70 UNION SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74
    UNION SELECT 75 UNION SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79
    UNION SELECT 80 UNION SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84
    UNION SELECT 85 UNION SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89
) seq
ON DUPLICATE KEY UPDATE 
    daily_visitors = VALUES(daily_visitors),
    daily_orders = VALUES(daily_orders),
    daily_revenue = VALUES(daily_revenue);

-- 初始化景区统计数据 (scenic_statistics)
-- 为每个景区生成最近90天的数据

-- 先清空旧数据
DELETE FROM scenic_statistics WHERE stat_date >= DATE_SUB(CURDATE(), INTERVAL 90 DAY);

-- 为景区ID 1-5 插入数据
INSERT INTO scenic_statistics (scenic_id, stat_date, visitor_count, order_count, revenue, favorites_count, avg_stay_time, weather, is_weekend, is_holiday, created_at)
SELECT 
    scenic.id as scenic_id,
    DATE_SUB(CURDATE(), INTERVAL seq.seq DAY) as stat_date,
    -- 游客量：根据景区热度调整，周末更高
    CASE 
        WHEN DAYOFWEEK(DATE_SUB(CURDATE(), INTERVAL seq.seq DAY)) IN (1, 7) 
        THEN FLOOR(300 + RAND() * 500 + scenic.base_visitors * 0.3)
        ELSE FLOOR(150 + RAND() * 300 + scenic.base_visitors * 0.2)
    END as visitor_count,
    -- 订单量
    CASE 
        WHEN DAYOFWEEK(DATE_SUB(CURDATE(), INTERVAL seq.seq DAY)) IN (1, 7) 
        THEN FLOOR((300 + RAND() * 500) * 0.6)
        ELSE FLOOR((150 + RAND() * 300) * 0.6)
    END as order_count,
    -- 收入
    CASE 
        WHEN DAYOFWEEK(DATE_SUB(CURDATE(), INTERVAL seq.seq DAY)) IN (1, 7) 
        THEN FLOOR((300 + RAND() * 500) * (60 + RAND() * 40))
        ELSE FLOOR((150 + RAND() * 300) * (60 + RAND() * 40))
    END as revenue,
    -- 收藏数
    FLOOR(5 + RAND() * 20) as favorites_count,
    -- 平均停留时间 2-4小时
    ROUND(2 + RAND() * 2, 1) as avg_stay_time,
    -- 天气
    ELT(FLOOR(1 + RAND() * 4), '晴', '多云', '阴', '小雨') as weather,
    -- 是否周末
    CASE WHEN DAYOFWEEK(DATE_SUB(CURDATE(), INTERVAL seq.seq DAY)) IN (1, 7) THEN 1 ELSE 0 END as is_weekend,
    -- 是否节假日
    0 as is_holiday,
    NOW() as created_at
FROM (
    SELECT 1 as id, 500 as base_visitors UNION
    SELECT 2, 400 UNION
    SELECT 3, 350 UNION
    SELECT 4, 300 UNION
    SELECT 5, 250
) scenic
CROSS JOIN (
    SELECT 0 as seq UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 
    UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9
    UNION SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14
    UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19
    UNION SELECT 20 UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24
    UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29
    UNION SELECT 30 UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34
    UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39
    UNION SELECT 40 UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44
    UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49
    UNION SELECT 50 UNION SELECT 51 UNION SELECT 52 UNION SELECT 53 UNION SELECT 54
    UNION SELECT 55 UNION SELECT 56 UNION SELECT 57 UNION SELECT 58 UNION SELECT 59
    UNION SELECT 60 UNION SELECT 61 UNION SELECT 62 UNION SELECT 63 UNION SELECT 64
    UNION SELECT 65 UNION SELECT 66 UNION SELECT 67 UNION SELECT 68 UNION SELECT 69
    UNION SELECT 70 UNION SELECT 71 UNION SELECT 72 UNION SELECT 73 UNION SELECT 74
    UNION SELECT 75 UNION SELECT 76 UNION SELECT 77 UNION SELECT 78 UNION SELECT 79
    UNION SELECT 80 UNION SELECT 81 UNION SELECT 82 UNION SELECT 83 UNION SELECT 84
    UNION SELECT 85 UNION SELECT 86 UNION SELECT 87 UNION SELECT 88 UNION SELECT 89
) seq
ON DUPLICATE KEY UPDATE 
    visitor_count = VALUES(visitor_count),
    order_count = VALUES(order_count),
    revenue = VALUES(revenue);
