package com.travel.controller.system;

import com.travel.common.Result;
import com.travel.dto.system.BackupInfo;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.stream.Collectors;

/**
 * 数据库备份管理接口
 */
@Slf4j
@RestController
@RequestMapping("/admin/backup")
@RequiredArgsConstructor
public class BackupController {

    @Value("${spring.datasource.url:jdbc:mysql://localhost:3306/travel_prediction}")
    private String dbUrl;

    @Value("${spring.datasource.username:root}")
    private String dbUsername;

    @Value("${backup.dir:./backups}")
    private String backupDir;

    /**
     * 获取备份列表
     */
    @GetMapping("/list")
    public Result<List<BackupInfo>> getBackupList() {
        try {
            File backupFolder = new File(backupDir);
            if (!backupFolder.exists()) {
                backupFolder.mkdirs();
                return Result.success(new ArrayList<>());
            }

            File[] files = backupFolder.listFiles((dir, name) -> name.endsWith(".sql"));
            if (files == null || files.length == 0) {
                return Result.success(new ArrayList<>());
            }

            List<BackupInfo> backupList = Arrays.stream(files)
                    .map(file -> {
                        BackupInfo info = new BackupInfo();
                        info.setId(file.getName().replace(".sql", ""));
                        info.setFilename(file.getName());
                        info.setDate(new Date(file.lastModified()));
                        info.setSize(formatFileSize(file.length()));
                        info.setSizeBytes(file.length());
                        info.setPath(file.getAbsolutePath());

                        if (file.getName().contains("manual")) {
                            info.setType("手动");
                        } else if (file.getName().contains("auto")) {
                            info.setType("自动");
                        } else {
                            info.setType("手动");
                        }

                        return info;
                    })
                    .sorted(Comparator.comparing(BackupInfo::getDate).reversed())
                    .collect(Collectors.toList());

            return Result.success(backupList);
        } catch (Exception e) {
            log.error("获取备份列表失败", e);
            return Result.error("获取备份列表失败: " + e.getMessage());
        }
    }

    /**
     * 创建手动备份
     */
    @PostMapping("/create")
    public Result<BackupInfo> createBackup(@RequestAttribute("userId") Long userId) {
        try {
            File backupFolder = new File(backupDir);
            if (!backupFolder.exists()) {
                backupFolder.mkdirs();
            }

            String dbName = extractDbName(dbUrl);
            String timestamp = new SimpleDateFormat("yyyy-MM-dd_HHmmss").format(new Date());
            String filename = String.format("backup_manual_%s_%s.sql", dbName, timestamp);
            String backupPath = backupDir + File.separator + filename;

            log.info("创建备份: {} by userId: {}", filename, userId);

            try {
                File backupFile = new File(backupPath);
                backupFile.createNewFile();

                try (FileWriter writer = new FileWriter(backupFile)) {
                    writer.write("-- MySQL Backup File\n");
                    writer.write("-- Database: " + dbName + "\n");
                    writer.write("-- Date: " + new Date() + "\n");
                    writer.write("-- Generated by Travel Prediction System\n\n");
                    writer.write("-- 注意：这是一个演示备份文件\n");
                    writer.write("-- 实际生产环境需要使用 mysqldump 工具\n");
                    writer.write("-- 命令示例：\n");
                    writer.write("-- mysqldump -u" + dbUsername + " -p " + dbName + " > " + filename + "\n\n");
                }
            } catch (IOException e) {
                log.error("创建备份文件失败", e);
                return Result.error("创建备份文件失败: " + e.getMessage());
            }

            File createdFile = new File(backupPath);
            long fileSize = createdFile.exists() ? createdFile.length() : 0;

            BackupInfo info = new BackupInfo();
            info.setId(filename.replace(".sql", ""));
            info.setFilename(filename);
            info.setDate(new Date());
            info.setSize(formatFileSize(fileSize));
            info.setSizeBytes(fileSize);
            info.setType("手动");
            info.setPath(backupPath);

            log.info("备份创建成功: {}, 大小: {}", filename, info.getSize());
            return Result.success(info, "备份创建成功（演示版本）");
        } catch (Exception e) {
            log.error("创建备份失败", e);
            return Result.error("创建备份失败: " + e.getMessage());
        }
    }

    /**
     * 下载备份文件
     */
    @GetMapping("/download/{filename}")
    public ResponseEntity<Resource> downloadBackup(@PathVariable String filename) {
        try {
            File file = new File(backupDir + File.separator + filename);

            if (!file.exists()) {
                log.error("备份文件不存在: {}", filename);
                return ResponseEntity.notFound().build();
            }

            Resource resource = new FileSystemResource(file);

            return ResponseEntity.ok()
                    .contentType(MediaType.APPLICATION_OCTET_STREAM)
                    .header(HttpHeaders.CONTENT_DISPOSITION,
                            "attachment; filename=\"" + filename + "\"")
                    .body(resource);
        } catch (Exception e) {
            log.error("下载备份失败: {}", filename, e);
            return ResponseEntity.internalServerError().build();
        }
    }

    /**
     * 删除备份文件
     */
    @DeleteMapping("/{filename}")
    public Result<Void> deleteBackup(@PathVariable String filename) {
        try {
            File file = new File(backupDir + File.separator + filename);

            if (!file.exists()) {
                return Result.error("备份文件不存在");
            }

            if (file.delete()) {
                log.info("删除备份成功: {}", filename);
                return Result.success(null, "删除成功");
            } else {
                return Result.error("删除失败");
            }
        } catch (Exception e) {
            log.error("删除备份失败: {}", filename, e);
            return Result.error("删除失败: " + e.getMessage());
        }
    }

    private String extractDbName(String url) {
        try {
            int lastSlash = url.lastIndexOf('/');
            if (lastSlash < 0) {
                return "database";
            }

            String afterSlash = url.substring(lastSlash + 1);

            int questionMark = afterSlash.indexOf('?');
            int ampersand = afterSlash.indexOf('&');

            int paramStart = -1;
            if (questionMark > 0 && ampersand > 0) {
                paramStart = Math.min(questionMark, ampersand);
            } else if (questionMark > 0) {
                paramStart = questionMark;
            } else if (ampersand > 0) {
                paramStart = ampersand;
            }

            return paramStart > 0 ? afterSlash.substring(0, paramStart) : afterSlash;
        } catch (Exception e) {
            log.error("提取数据库名失败: {}", url, e);
            return "database";
        }
    }

    private String formatFileSize(long size) {
        if (size < 1024) {
            return size + "B";
        } else if (size < 1024 * 1024) {
            return String.format("%.2fKB", size / 1024.0);
        } else if (size < 1024 * 1024 * 1024) {
            return String.format("%.2fMB", size / (1024.0 * 1024.0));
        } else {
            return String.format("%.2fGB", size / (1024.0 * 1024.0 * 1024.0));
        }
    }
}
