apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: ['service', 'job']
        spanStartTimeShift: -1m
        spanEndTimeShift: 1m
      tracesToMetrics:
        datasourceUid: prometheus

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - matcherRegex: 'traceId=([A-Za-z0-9]+)'
          name: TraceID
          url: '$${__value.raw}'
          datasourceUid: tempo
